### ISSUE TITLE
Strict mode for landing zone - narrow down network ACLs / security groups

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-landing-zone#184]
### Description

Context:
- Some network ACLs are more open that necessary - in particular there is a network ACL giving outbound access to any ip / any port given that it is not known in advance 
- This approach works for a number of consumers who do not need to strictly follow the FsCloud framework, and use landing zone as a starting point
- This approach however is problematic for consumers expecting a fully-locked down environment out of the box, eg: consumers strictly following the FsCloud framework.

Idea:
- Include a "strict" mode in landing zone - for instance in the form of an input boolean
- In "strict" mode, the network ACLs are fully close to the bar minimum to allow communication between the components created by the landing zone module.

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by vburckhardt** [comment]
The default sg (created as part of the VPC) is also associated by default to the worker nodes (in addition to the custom kube-<clusterID>). This default sg has got a outbound wide open (0.0.0.0). Some customers are currently closing this one down manually, but it would be worth doing this programmatically through slz logic.

Also:
- On 4.9, the kube-<cluster> sg does not contain the rules allowing communication with master VPE. On 4.9, there is a reliance on the default sg rule for basic in-cluster connectivity
- On 4.11, the kube-<cluster> sg seems to contain all minimum rules and removing rules from default sg does not seem to affect health of the cluster.

( Note tested 4.10).

Therefore, one approach here would be to not add the default sg. There seems to be a recent addition in OCP allowing this - see https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-security-group#cluster-sg-only

**Comment by Ak-sky** [comment]
This is included in -
https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/issues/357
and
https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/issues/393

**Comment by Ak-sky** [comment]
This is included in - [Ticket 1](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/issues/357)  and  [Ticket 2](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/issues/393).
