### ISSUE TITLE
Papercut: Missing automated tests for vsi standard pattern and upgrade tests for no-compute

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-landing-zone#354]
### Description

https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/main/tests/pr_test.go is currently missing:
- Tests for the vsi pattern (idempotency and upgrade) https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/tree/main/patterns/vsi
- Upgrade tests for the no compute example

**Comment by Soaib024** [comment]
PR merged - hence closing

**Comment by Khuzaima05** [comment]
PR merged
