### ISSUE TITLE
Papercut: Lookup for ssh_public_key if the one passed as input already exists in account / region

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-landing-zone#355]
### Description

This is a recurring issues with many consumers where the ssh_public_key that is passed as input already exists in the account. Backend returns with an error stating that key already exists. 

Investigate whether we could do a better job at the terraform layer by looking up the existing keys in account and using https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/is_ssh_keys and comparing with the key passed as input.

**Comment by imprateeksh** [comment]
Closing the issue as PR is merged.
