### ISSUE TITLE
Papercut: default vsi image is relatively old (and in deprecated status)

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-landing-zone#361]
### Description

Update to latest supported ubuntu image  as the default for the image. - eg: "ibm-ubuntu-22-04-1-minimal-amd64-4" as per ibmcloud is images

Current default is ibm-ubuntu-18-04-6-minimal-amd64-2 at https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/f8b5627999c7c16aa64b7314cc6342fdab899145/patterns/vsi/variables.tf#L122

Suggest to make the image field as not tracked in terraform as well if this is not the case (otherwise this is a breaking change with new major release everytime we update image version is reference arch)

**Comment by Soaib024** [comment]
PR merged - hence closing
