### ISSUE TITLE
Adjust references to Activity Tracker events to Cloud Object storage

### ISSUE THREAD

**Issue by cmore231** [terraform-ibm-modules/terraform-ibm-landing-zone#424]
### Description

The references to Activity Tracker Cloud Object Storage need to be corrected here:
https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/main/reference-architectures/deploy-arch-ibm-slz-ocp.md
https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/main/reference-architectures/deploy-arch-ibm-slz-vpc-standard.md
https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/main/reference-architectures/deploy-arch-ibm-slz-vsi-standard.md
https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/main/reference-architectures/roks.drawio.svg
https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/main/reference-architectures/vpc.drawio.svg
https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/main/reference-architectures/vsi-vsi.drawio.svg

The service used to send Activity Tracker events to Cloud Object storage is Activity Tracker event routing.

One issue is Activity Tracker event routing icon is not yet in https://github.ibm.com/ibmcloud/ibm-cloud-stencils

Phil.MacLaren@ibm.com is working on the icon for Activity Tracker event routing and should be able to provide an official icon.

### New or affected modules

N/A
---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by SirSpidey** [comment]
See information from @phil.MacLaren@ibm.com in [internal Slack](https://ibm-cloudplatform.slack.com/archives/C1UAU5NNP/p1682696949318299?thread_ts=1680495001.232119&cid=C1UAU5NNP)

**Comment by SirSpidey** [comment]
Work to update the diagrams to v2 standard: https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/468

**Comment by alex-reiff** [comment]
Spoke with Jose, the generic icon AT uses for event routing is not yet in our library.

**Comment by SirSpidey** [comment]
@cmore231 I think we addressed the issues here a while ago. Take a look at the reference architectures in the description. Let me know if this needs to be reopened.
