### ISSUE TITLE
Request for Subnet CRN as part of terraform output

### ISSUE THREAD

**Issue by digvijay-ukirde** [terraform-ibm-modules/terraform-ibm-landing-zone#500]
### Description

Our project needs to integrate the DNS service with the Landing zone. One of the components (custom resolver) needs subnet CRN as input, so requesting to provide it as part of the landing zone output.
Reference: https://ibm-cloudplatform.slack.com/archives/C02SDGCJAB1/p1689206583231449 

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
Included in https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/pull/587
