### ISSUE TITLE
Support for existing encryption keys referenced by CRN

### ISSUE THREAD

**Issue by in-1911** [terraform-ibm-modules/terraform-ibm-landing-zone#510]
### Description

Enable support for using an existing key referenced by CRN in the override.json (`key_management.keys` element).
This will allow to use a cross-account KeyProtect / HPCS Instances where there may be no full visibility to the KMS instance, but the keys are available by CRN.

- If a CRN of a key is provided, no KMS instance should be required to look up the key, the key CRN is just included in the key map to be used in other modules referencing it by name
- The landing zone should support a scenario where no KMS instance is supplied but a set of existing keys with CRNs is provided in override.json (`key_management.keys` element)
- The landing zone should support a mixed scenario where some keys are supposed to be created while some are provided with CRNs.

### New or affected modules

- kms/variables.tf - add crn attributes as optional(string) to the variable schema
- kms/outputs.tf - key_map should be a union of keys created with references of existing keys that CRNs were provided for
- kms/dynamic_values/main.tf - key_management_keys, key_rings, and key_management_key_policies should only include items for which keys would be actually created. Key items with existing CRNs are omitted from those lists.

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by Aashiq-J** [comment]
@in-1911 ,
When a kms instance is not provided slz goes ahead and creates the kms instance as it is required by the cluster as we need to attach a Key Protect instance to the cluster.
https://registry.terraform.io/providers/JonWoodlief/ibm/latest/docs/resources/container_vpc_cluster#create-a-kms-enabled-kubernetes-cluster

So, I think its not possible to not pass a kms instance, but we can use existing kms instance or create a new one.
I can go ahead and implement the feature of using existing key crn.

**Comment by ocofaigh** [comment]
@in-1911 Looking at the api (https://cloud.ibm.com/apidocs/kubernetes/containers-v1-v2#createkmsconfig) it shows required for `instanceID` and `crkID`, however it does support passing `accountID` which is supposed to be used if the KMS instance is in another account. We have created an enhancement request with the IBM terraform provider to see if they will add support to pass an account ID for this use case -> https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4745

**Comment by ocofaigh** [comment]
@in-1911 In order to encrypt the cluster using a KMS key from a different account, a cross account auth policy would need to be created. Is this something you feel SLZ should create too when we add cross account encryption support. I'm guessing yes since it currently supports creating all the local auth policies?

**Comment by in-1911** [comment]
I do not think the cross account access policy would be created via SLZ. It needs to be done in a different account and probably by a different team. I.e. when a "business unit" deploys a landing zone in a sub-account, the Service Hub admins will need to grant access to the central KMS. For other services (like COS) the Hub admins would also need to create the keys and pass the CRNs to the "business unit" team.

I am completely fine if the cross-account grant or key creation in Service Hub is a prerequisite to deploying Landing Zone with central KMS instance.

**Comment by ocofaigh** [comment]
Yes good point, the auth policy creation would have to be done in the account where the KMS instance exists. So this will have to be a prerequisite that we can document. 

I'll work with @Aashiq-J and team internally to design a solution here.

**Comment by ocofaigh** [comment]
@in-1911 Wanted to give you a quick update on our findings...

Currently the IBM provider does not support passing an account ID in the cluster encryption block. It only supports:
```
  kms_config {
      instance_id = "12043812-757f-4e1e-8436-6af3245e6a69"
      crk_id = "0792853c-b9f9-4b35-9d9e-ffceab51d3c1"
      private_endpoint = false
  }
```
We are going to create an enhancement request with the provider on this.

The provider does however support passing an account ID for the encryption of the worker nodes boot volumes:
![image](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/assets/29608224/18e7136c-be9c-4434-b1f5-a7118320ebe0)

However, SLZ actually doesn't currently have support in the code to encrypt the boot volumes. This is something we are not going to add.

While we wait for provider support to pass an account ID for cluster encryption, we are going to add support to the override.json for VSI and VPC to use a root key crn from a different account. Once implemented, I will share the details on how to consume with you.

**Comment by ocofaigh** [comment]
PR under review for this https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/542/files

**Comment by in-1911** [comment]
@ocofaigh @Aashiq-J - sorry for a bit of mix-up, I did not notice a new PR by @Aashiq-J and went ahead with my own, although taking some pointers from @Aashiq-J work. I think I did resolve a couple of additional issues in my code as well, so a review of #553 would be appreciated.

**Comment by Aashiq-J** [comment]
Hi @in-1911 ,

We have decided to go ahead with this approach(https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/547).
Appreciate you for your PR, but its missing a lot of components, which are addressed in  this [PR](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/547)
Could you please list the issues you found in this [PR](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/547), so that we can address it.
Thanks.

**Comment by in-1911** [comment]
@Aashiq-J - no problem with going ahead with #547 , but you might take a few points from mine (#553) to address some of the minor issues:
- The condition for S2S authorization needs to use something directly related to inputs, otherwise TF complains about the count condition in some scenarios - I set `local.target_key_management_service`  to null in `(dynamic_values/config_modules/service_authorizations/service_authorizations.tf)` if no KMS name is provided  `  [see here](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/553/files#diff-21b57eb683b6b06d1bbf54b6717d14ae1c079439bc60efa7dcab3c7802dfefee). Then you check `local.target_key_management_service` instead of the KMS guid in the counts for s2s authorizations.
- The KMS dynamic values unit tests do not need to be disabled, but you need to pass the name attributes when a "resource" test is done - [see here](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/553/files#diff-00e52fc271ed09e90efdac97b418c72efe987cc4000441ce05dba307fc369168)
- I added some notes on the key parameters and the KMS instance logic in the [README](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/553/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
- I did not include that, but if you are changing the cos module, use the `kms_key_crn` parameter instead of `key_protect` (see note above [the example](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/cos_bucket#example-usage-3))

The rest of my changes are pretty much identical to yours

**Comment by Aashiq-J** [comment]
Status: The PR is under internal team review.

**Comment by Aashiq-J** [comment]
PR merged. Feature available in latest release.
https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/releases/tag/v4.9.0
