### ISSUE TITLE
Upgrade VSI module version to enable proper resource group for data volumes

### ISSUE THREAD

**Issue by in-1911** [terraform-ibm-modules/terraform-ibm-landing-zone#533]
### Description

Due to an inconsistency in the VSI module (see https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vsi/issues/504) the data volumes are always created in Default resource group.
The VSI module 2.5.0 changes the default behavior to use VSI's RG, which would be more consistent.

The caveat may be that the upgrade of the DA could cause data volumes to be recreated, however the current version makes using data volumes in VSI config in landing zone practically useless if one want to keep the VPC resources assigned to proper resource groups.

### New or affected modules

virtual_servers.tf - upgrade the terraform-ibm-modules/landing-zone-vsi/ibm module version to 2.5.0

---

**Comment by ocofaigh** [comment]
@in-1911 Yea I had the same concern that it will probably destroy and recreate the volumes. Our upgrade test should catch this when we update to use 2.5.0. I'll speak with the team on how to handle this. If someone didnt wan't their volumes destroyed right now, they could technically specify "Default" resource group in the `block_storage_volumes` variable.

**Comment by ocofaigh** [comment]
I created a [draft PR](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/535/files) in order to see how the tests behaved, however it keeps failing with:
```
Error: [ERROR] Error while creating key ring : kp.Error: correlation_id='c2279492-4217-4ff0-8d86-e5ac86c35441', msg='Unauthorized: Either the user does not have access to the specified resource, the resource does not exist, or the region is incorrectly set'
```
Need to reproduce locally and debug
