### ISSUE TITLE
Expose global attribute for transit gateway creation

### ISSUE THREAD

**Issue by surajsbharadwaj** [terraform-ibm-modules/terraform-ibm-landing-zone#552]
With the new Networking capabilities in PowerVS side, Power edge router,
we have a feature request:

is it possible to expose **`global`** attribute for` ibm_tg_gateway` variable for `transit gateway` in override json ? Currently it is set to false [here](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/02648ac36c2eb15d9bceb8c43f200c6418a38735/transit_gateway.tf#L10).

**Comment by akocbek** [comment]
@surajsbharadwaj 

feature is supported from [v4.8.0](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/releases/tag/v4.8.0) version
