### ISSUE TITLE
Description says 16 but test checks for 13 characters in prefix for ROKS landing zone

### ISSUE THREAD

**Issue by l2fprod** [terraform-ibm-modules/terraform-ibm-landing-zone#555]
While deploying the ROKS landing zone today:

![image](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/assets/12746550/234d21cb-85f6-4474-ad71-171cf6a76ab9)

![image](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/assets/12746550/b9df8d82-70c5-434a-997b-948479efc676)

---

the description
https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/02648ac36c2eb15d9bceb8c43f200c6418a38735/patterns/roks/variables.tf#L12

the test
https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/02648ac36c2eb15d9bceb8c43f200c6418a38735/patterns/roks/variables.tf#L17

**Comment by ocofaigh** [comment]
Fixed in https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/568
