### ISSUE TITLE
Missing documentation for the override_json_string

### ISSUE THREAD

**Issue by l2fprod** [terraform-ibm-modules/terraform-ibm-landing-zone#556]
I noticed I could customize the landing zone with a JSON string

<img width="608" alt="image" src="https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/assets/12746550/c4dc172c-3ba6-41a9-a7b4-92f2b273a3e7">

How do I find the syntax?

The help tooltip has no link to further documentation

I clicked `Docs`

<img width="600" alt="image" src="https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/assets/12746550/c4b74c48-0dff-4fe3-ad70-dbb58fe07ef5">

And searched for `override_json_string`

<img width="1592" alt="image" src="https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/assets/12746550/c1ab5311-88ff-4e02-b695-d29973982951">

I would expect a full description of the JSON file format in the documentation and hyperlinked from the variable tooltip

**Comment by vburckhardt** [comment]
@SirSpidey - Suggest starting from here https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone#customizing-by-using-the-overridejson-file . We can also link to the wizard (currently under https://ibm.biz/slzwizard ) in the doc when it GA later this year.

**Comment by SirSpidey** [comment]
Current idea is to add a Learn more link to the override description "tooltip". That link can go to the [new tutorial](https://github.ibm.com/Bluemix/docs/issues/10318) that's planned for Q4

**Comment by SirSpidey** [comment]
Updates to override variable descriptions are merged. Waiting for release of the deployable architectures for them to be available in the catalog. 

Updates in the variables include a link to the [landing zone configuration tool](https://terraform-ibm-modules.github.io/landing-zone-config-tool/#/home)
