### ISSUE TITLE
Include cluster IDs and other infrastructure information as outputs

### ISSUE THREAD

**Issue by luisarojas** [terraform-ibm-modules/terraform-ibm-landing-zone#605]
### Description

After making use of this module for our team's automation, we see value in adding all the **ID** of all clusters created as outputs. Currently, only **names** are included.

Moreover, it would also be very helpful if there was a way to map the clusters created to the resource group they were created in. Currently, there are two _separate_ arrays: One for cluster names and another for resource group names.

Perhaps a complex object that includes VPC, region, resource group and cluster?

### New or affected modules

https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
PR under review if you wanted to have a preview @luisarojas https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/606

**Comment by luisarojas** [comment]
Hey @Aashiq-J @ocofaigh,

How about something like this? I think this way there would be less redundant data, considering that:
* CRNs can be inferred from IDs, for both VPCs and clusters.
* Resource group name can be inferred from resource group ID.
* Resource group and region for a cluster depends for the VPC that it is a part of; and all clusters in that VPC will have the same information.
* Always favour using IDs instead of names, especially if they will be used as object keys. I'm not using this in the proposal below, but in the case that you do want to go the route of a large nested object, I strongly suggest you use clusters IDs instead of names as the key.
Anyway, what are your thought on something like this?

In an array of VPCs:
```
[
  {
	"id" = "r018-f0249f19-7ff4-4675-5f310e0429e6",
	"resource_group_id" = "bb23c29b8345vdsdf2345a75faa7282".
	"region" = "eu-gb",
	"clusters" = [
		"ckj4534berebfgddfhlg90"
	]
  },
  {
	"id" = "r018-0c202cba-5ed9-43d9-870254000294",
	"resource_group_id" = "d7ef1d4c2345wdfsddfebe8b05359",
	"region" = "eu-gb",
	"clusters" = [
		"ckjcf54bethrvrydb59g"
	]
  }
]
```

**Comment by Aashiq-J** [comment]
Added new output
```
vpc_resource_list = [
  {
    "clusters" = [
      "ckmii89s03469jb01fd0",
    ]
    "id" = "r026-ab6f85aa-52ac-4681-b25e-88ac76a56b49"
    "name" = "roks-test-management-vpc"
    "region" = "au-syd"
    "resource_group_id" = "ab96da73758240f3aae793c81c5ea982"
    "vsi" = tolist([])
  },
  {
    "clusters" = [
      "ckmii6ps0tpf4cmht60g",
    ]
    "id" = "r026-9ae95bca-1109-4ce5-82db-2f4891aa181b"
    "name" = "roks-test-workload-vpc"
    "region" = "au-syd"
    "resource_group_id" = "7c40cb0e076947be91b0461349c91f5c"
    "vsi" = tolist([])
  },
]
```

**Comment by ocofaigh** [comment]
@luisarojas happy enough with new proposed output? Changes have been pushed to https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/606 if you wanted to review?

**Comment by luisarojas** [comment]
@ocofaigh Looks good to me, thanks.

**Comment by Aashiq-J** [comment]
PR merged. Closing issue
