### ISSUE TITLE
Investigate how (if) we can use new existing VPC / subnets in SLZ

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-landing-zone#635]
In https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/releases/tag/v7.12.0 support was added to be able to use existing VPC and/or subnets. We need to investigate if it is possible to add this support to the main SLZ solution. This is a requirement from the HPC team, as per https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/issues/599

**Comment by toddgiguere** [comment]
Solved and released:

* Added two new optional properties to the existing vpcs input map to supply existing vpc and subnet IDs
* Fixed any dynamic values mappings that were assuming the subnet names were in the form of {prefix}-{vpcname}-{subnet_name}, preferring instead to look up subnets by {subnet_name} in any part of regex
* Upgraded to latest LZ VPC module that fully supports existing VPCs or subnets

NOTE: feature was not passed up into patterns. This is a feature only available if calling SLZ module directly or via pattern override of vpcs map.

https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/releases/tag/v5.5.0
