### ISSUE TITLE
Missing kube->kms s2s policy

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-landing-zone#645]
That specific s2s policy does not seem to be created by the module code itself.

On a fresh account:
again.","type":"Authentication"}
 2023/11/30 15:45:51 Terraform apply | 
 2023/11/30 15:45:51 Terraform apply |   with module.roks_landing_zone.module.landing_zone.ibm_container_vpc_cluster.cluster["wxai-management-cluster"],
 2023/11/30 15:45:51 Terraform apply |   on ../../cluster.tf line 34, in resource "ibm_container_vpc_cluster" "cluster":
 2023/11/30 15:45:51 Terraform apply |   34: resource "ibm_container_vpc_cluster" "cluster" {
 2023/11/30 15:45:51 Terraform apply | 
 2023/11/30 15:45:51 Terraform apply | 
 2023/11/30 15:45:51 Terraform apply | Error: Request failed with status code: 401, ServerErrorResponse: {"incidentID":"dc3c5793-4641-44a6-a2d8-699335dbf0f9","code":"E09c0","description":"Not authorized to access the Key Management Service. Create an IBM Cloud IAM authorization policy to give the source Kubernetes Service delegate access to the target Key Management Service, and try again.","type":"Authentication"}
 2023/11/30 15:45:51 Terraform apply | 
 2023/11/30 15:45:51 Terraform apply |   with module.roks_landing_zone.module.landing_zone.ibm_container_vpc_cluster.cluster["wxai-workload-cluster"],
 2023/11/30 15:45:51 Terraform apply |   on ../../cluster.tf line 34, in resource "ibm_container_vpc_cluster" "cluster":
 2023/11/30 15:45:51 Terraform apply |   34: resource "ibm_container_vpc_cluster" "cluster" {
 2023/11/30 15:45:51 Terraform apply | 
 2023/11/30 15:45:51 [1m[31mTerraform APPLY

**Comment by ocofaigh** [comment]
@vburckhardt @Ak-sky This policy is supposed to be auto created when you provision a new cluster. It creates the following global auth policy:
![image](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/assets/29608224/2f337ff1-800d-45e2-97a9-9273a262eb7b)

So hence that is why we don't create it in our code.

**Comment by Ak-sky** [comment]
- [PR](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/721) merged, closing this.
- Updated the comment in code [here](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/319b557559f1cb11ceabb1111f4087c494c03ae7/dynamic_values/config_modules/service_authorizations/service_authorizations.tf#L62) on why there is a need to create an s2s kube -> kms auth policy explicitly.
