### ISSUE TITLE
Can we have the public gateway id created by DA in landing zone output please?

### ISSUE THREAD

**Issue by nupurg-ibm** [terraform-ibm-modules/terraform-ibm-landing-zone#682]
### Description

Can we have the public gateway id created by DA in landing zone output please? 
We don't need existing subnet's public gateway id there. So if no public gateway got created by landing zone, null could be the default output.
It would be helpful if output contains respective zone numbers as well, something like this:

```
output "public_gateway_id" {
    value  = {
    "zone-1" = pg_id //As only for zone-1 public gateway got created via landing zone.
    "zone-2" = null
    "zone-3" = null
  }
}
```

**Comment by toddgiguere** [comment]
The public gateways created by base module landing zone are already being output in the `vpc_data` output variable.

`vpc_data` is an array of VPC objects, and in each VPC object there is a `public_gateways` map with network zone as key and the gateway ID as the value, with a "null" representing a zone that was not configured for a gateway.
Example `terraform output vpc_data` (zone 1 and 2 have gateways):
```
[
  {
    "vpc_id" = "your-vpc-id"
    "vpc_name" = "your-vpc-name"
    "public_gateways" = {
      "zone-1" = "zone-1-gateway-id"
      "zone-2" = "zone-2-gateway-id"
      "zone-3" = null
    }
  }
]
```

If we do have a dedicated public gateway output variable, it will need to support multiple VPCs, probably a map of maps (or list of maps), which is how `vpc_data` is organized already, so I'm not sure if a dedicated output is needed.

**Comment by ocofaigh** [comment]
@nupurg-ibm are you ok with this, can we close this issue?

**Comment by nupurg-ibm** [comment]
yes please

**Comment by toddgiguere** [comment]
Closing with no changes made, see above comment for location of public gateway ID outputs in VPC blocks.
