### ISSUE TITLE
Allow to specify secondary storage in ocp flavor

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-landing-zone#688]
### Description

Surface the secondary storage field https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/container_vpc_worker_pool#secondary_storage in landing zone interface (via override.json). Currently missing https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/7e685180f34389ef45c22e7bafb74ead5ab0be8c/cluster.tf#L112

**Comment by hiltol** [comment]
How soon could this be available?

**Comment by jor2** [comment]
> How soon could this be available?

Check out https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/releases/tag/v5.13.0
