### ISSUE TITLE
Add Support for CBRs

### ISSUE THREAD

**Issue by priyanknarvekar** [terraform-ibm-modules/terraform-ibm-landing-zone#754]
### Description

SCC has started scanning for CBRs enforcement in accounts. Landing zone should support creation of cbrs.

Terraform support for the cbr rules is present:
- https://registry.terraform.io/providers/ibm-cloud/ibm/latest/docs/resources/cbr_rule

**Comment by ocofaigh** [comment]
@priyanknarvekar Its something we are already looking at. Please be aware that we already have a CBR module at https://github.com/terraform-ibm-modules/terraform-ibm-cbr

**Comment by ocofaigh** [comment]
Support has been added in [v5.33.0](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/releases/tag/v5.33.0) which will add the VPCs to an existing CBR zone.
We recommend to use the [terraform-ibm-cbr](https://github.com/terraform-ibm-modules/terraform-ibm-cbr) module to create the CBR zones and rules. Take note of the [Pre-wired CBR configuration for FS Cloud](https://github.com/terraform-ibm-modules/terraform-ibm-cbr/tree/main/modules/fscloud) submodule.
