### ISSUE TITLE
Add support for PAG

### ISSUE THREAD

**Issue by priyanknarvekar** [terraform-ibm-modules/terraform-ibm-landing-zone#755]
### Description

PAGs are required by customer when creating a production deployement. We need to support creation of PAG via landing zone. 

Terraform provider does support it - https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/pag_instance

**Comment by ocofaigh** [comment]
@priyanknarvekar I don't think landing zone will support creating PAG, however we will have a standalone PAG module (and eventually a DA). PAG is not yet publicly available, however do have an internal PAG module if you want to reach out if you are an internal IBMer
