### ISSUE TITLE
Add Support for DNS

### ISSUE THREAD

**Issue by nupurg-ibm** [terraform-ibm-modules/terraform-ibm-landing-zone#761]
### Description

DNS implementation is there with landing-zone-vpc module and it would be great to have that same here with root module as well

### New or affected modules

DNS integration can be introduced with following variables, and other dependent variables if needed:

1. [dns_binding_name](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/tree/main#input_dns_binding_name)
2. [dns_custom_resolver_name](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/tree/main#input_dns_custom_resolver_name)
3. [dns_instance_name](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/tree/main#input_dns_instance_name)
4. [dns_location](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/tree/main#input_dns_location)
5. [dns_plan](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/tree/main#input_dns_plan)
6. [existing_dns_instance_id](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/tree/main#input_existing_dns_instance_id)

Note: We have [existing_dns_instance_id](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/tree/main#input_existing_dns_instance_id) which takes Id of an existing dns instance in which the custom resolver is created.  Can we just provide existing dns instance id and new custom resolver gets created or vice versa [giving existing custom resolver with existing vpc and new dns instance gets created]? 

Can we introduce another variable for this like existing_custom_resolver_id as well?

**Comment by MatthewLemmond** [comment]
https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/795
