### ISSUE TITLE
fix images roks.drawio.svg

### ISSUE THREAD

**Issue by vaseemw** [terraform-ibm-modules/terraform-ibm-landing-zone#804]
Following needs to be fixed in reference-architectures/roks.drawio.svg

![image](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/assets/49982181/a74a6b45-12b6-4c8c-81bc-a9e7746d7f38)

The IP to be changed to 10.30.10.0

**Comment by ocofaigh** [comment]
PR: https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/807

**Comment by ocofaigh** [comment]
PR merged - closing
