### ISSUE TITLE
Add `management_events` to COS bucket creation code in SLZ

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-landing-zone#820]
In https://github.com/IBM-Cloud/terraform-provider-ibm/pull/5277 they are adding support for `management_events` in the AT config.

Once added, we will want to update code in two places:
- https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/a2a4565c0c265db0fc36b8e418b7ca367a08dacb/cos.tf#L140-L144
- https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/a2a4565c0c265db0fc36b8e418b7ca367a08dacb/variables.tf#L540-L544

**Comment by ocofaigh** [comment]
The provider PR was merged today, so this should be ready to go in 1.67.0

**Comment by kierramarie** [comment]
Starting on update.
