### ISSUE TITLE
Seeing low on ephemeral-storage resource on a node

### ISSUE THREAD

**Issue by NatarajBTI** [terraform-ibm-modules/terraform-ibm-landing-zone#825]
Seeing low on ephemeral-storage resource on a node & pod status is showing "Evicted". This is causing install of our MAS application to fail. Below attached override.json file is used in cluster creation.

[override.json](https://github.com/user-attachments/files/15927824/override.json)

![image](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/assets/57617912/e9017e20-f531-46eb-8f3d-51834ad0e955)

![image](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/assets/57617912/ad3de54f-60ad-4851-a52b-bdf901f9e939)

**Comment by ocofaigh** [comment]
@NatarajBTI An ephemeral storage error is something to do with your workload, not the cluster thats running it. Perhaps take a look at https://stackoverflow.com/a/59907080
