### ISSUE TITLE
Secondary storage isn't getting attached to the cluster from v6.0.0 product version

### ISSUE THREAD

**Issue by NatarajBTI** [terraform-ibm-modules/terraform-ibm-landing-zone#887]
Please note that secondary storage isn't getting attached to the cluster from v6.0.0 product version of Red Hat OpenShift Container Platform on VPC landing zone.
Please see below attached screenshot.
It used to attach the 300 GB secondary storage in previous product versions such as v5.31.2.
I was using the same override.json file for cluster creation before too.

**Comment by NatarajBTI** [comment]
[override.json](https://github.com/user-attachments/files/17097311/override.json)
![image (418)](https://github.com/user-attachments/assets/b1b99291-6ad9-4226-9833-9b951b9604d6)

**Comment by ocofaigh** [comment]
Fixed in v6.0.1
