### ISSUE TITLE
Workload cluster name is not returned in output

### ISSUE THREAD

**Issue by in-1911** [terraform-ibm-modules/terraform-ibm-landing-zone#888]
https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/51b4d11660953914db447e12d5b98aad244a7d5a/outputs.tf#L90

When the module is used via the ROKS on VPC landing zone DA (as part of the RAG Stack), the workload cluster name output is empty although other cluster attributes (cluster ID) are returned.

The case I tested included `vpcs = ["workload"]` and `ignore_vpcs_for_cluster_deployment = []` (i.e. one VPC with a cluster)

**Comment by in-1911** [comment]
![image](https://github.com/user-attachments/assets/942542e2-2bcc-4457-a3cb-d0d225314757)

**Comment by ocofaigh** [comment]
In v6.0.1
