### ISSUE TITLE
Add links in VPC landing zone description

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-landing-zone#923]
### Description

Suggest to add links to the 2 mentioned DA in VPC landing zone description
![image](https://github.com/user-attachments/assets/12579401-f009-4087-9511-14558664604e)

**Comment by arya-girish-k** [comment]
Merged this [PR](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/939).Closing the issue

**Comment by arya-girish-k** [comment]
Merged this https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/939.Closing the issue
